# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrategias', '0010_objetivo_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='actoresrelevantes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
    ]
